# The name of the site will be used to reference theme files.
NAME: "message-lab-theme"

# Your project's server will run on localhost:xxxx at this port
PORT: 3000

# Folder to clean up before running scripts.
CLEAN:
  - "css"

# Environments
ENVIRONMENTS:
  development: "message-lab.dd:8083"
  staging: "message-lab.apps.staging.digital.gov.au"
  production: "message-lab.apps.staging.digital.gov.au"

# Autoprefixer will make sure your CSS works with these browsers
COMPATIBILITY:
  - "last 2 versions"
  - "ie >= 8"

# Gulp will reference these paths when it copies files
PATHS:
  themesRoot: "/themes/custom/"
  jsRoot: "/js/"
  cssRoot: "/css/"
  sassRoot: "/sass/"
  sass:
    - "sass/message-lab-theme.style.scss"
    - "node_modules/normalize.css"
    - "node_modules/susy/sass"
    - "pancake/sass"
